version: '3'
services:
  rdb:
    image: rethinkdb:latest
    ports:
      - 8080:8080
      - 28015:28015
  devcontrackr-server:
    image: devcontrackr/server
    environment:
      - RDB_HOST=rdb
      - RDB_PORT=28015
    ports:
      - 3000:3000
    depends_on:
      - rdb
    links:
      - rdb:rdb
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    command: npm run dev
  devcontrackr-client-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - 8080:8080
    depends_on:
      - devcontrackr-server
    links:
      # check this "link" below because I don't really see it clear
      - devcontrackr-server
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    command: npm run dev
